export enum EContractStatus {
    PENDING = "PENDING",
    IN_PROGRESS = "IN_PROGRESS",
    FINISHED = "FINISHED",
    CANCELLED_BY_CLIENT = "CANCELLED_BY_CLIENT",
    CANCELLED_BY_WORKER = "CANCELLED_BY_WORKER"
}