export interface Tasker {
    bank: string;
    bankAccount: string;
    biography: string;
    birthdate: Date;
    city: string;
    country: string;
    createAt: Date;
    deviceId: string;
    documentNumber: string;
    documentPicture: string;
    documentType: string;
    email: string;
    experience: string;
    firstname: string;
    gender: string;
    id: string;
    isActive: boolean;
    isPayed: boolean;
    isVerified: boolean;
    lastname: string;
    membership: string;
    membershipRedeemable: boolean;
    password: string;
    phoneExtension: string;
    phoneNumber: string;
    version: string;
    profilePicture: string;
    qualification: number;
    subcategoryPrices: SubcategoryPrice[];
    updateAt: Date;
    deviceInfo: any;
};

export interface SubcategoryPrice {
    categoryId: string;
    price: number;
    subcategoryId: string;
    subcategoryName: string;
};